[pytest]
markers =
    positive: позитивные тесты
    negative: негативные тесты
    smoke: быстрые тесты
    regression: регрессионные тесты
    slow: медленные тесты
    api: API-тесты
    ui: Интерфейс-тесты
    db: База данных тесты
    auth: Тесты авторизации
    movies: Тесты для фильмов
    delete_movie: Тесты удаления фильмов
    change_movies: Тесты изменения фильмов
    change_reviews: Тесты изменения отзывов
    review_visibility: Тесты видимости отзывов
    delete_review: Тесты удаления отзывов
    delete_genre: Тесты удаления жанров
    get_movies: Тесты получения фильмов
    get_movie: Тесты получения конкретного фильма
    get_review_movie: Тесты получения отзывов
    get_list_genres: Тесты получения списка жанров
    get_genre: Тесты получения конкретного жанра
    parametrized: Параметризованные тесты
    filter_tests: Тесты фильтрации
    crud: CRUD операции
    crud_full: Полный CRUD цикл
    Cinescope: Учебный проект
    flaky: Тесты, которые иногда падают (с повторами)
    pagination: Тесты пагинации
    create_movie: Тесты создания фильмов
    create_review: Тесты создания отзывов
    create_genre: Тесты создания жанров
    movies: Тесты всех фильмов

log_cli = 1
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format=%Y-%m-%d %H:%M:%S